"""
Component Type Registry
Defines all available component types, their categories, and default properties
"""

class ComponentType:
    """Component type definitions with metadata"""
    
    # Primitive Components (HTML elements - fully composable)
    BUTTON = "button"
    INPUT = "input"
    TEXTAREA = "textarea"
    SELECT = "select"
    CHECKBOX = "checkbox"
    RADIO = "radio"
    TEXT = "text"
    HEADING = "heading"
    PARAGRAPH = "p"
    SPAN = "span"
    LABEL = "label"
    LINK = "a"
    IMAGE = "img"
    ICON = "icon"
    BADGE = "badge"
    AVATAR = "avatar"
    CARD = "card"
    LIST = "list"
    LIST_ITEM = "li"
    DIVIDER = "divider"
    
    # Layout Components
    DIV = "div"
    SECTION = "section"
    CONTAINER = "container"
    GRID = "grid"
    FLEX = "flex"
    STACK = "stack"
    
    # Composite Components (Complex - props-based)
    CHART = "chart"
    DASHLET = "dashlet"
    TABLE = "table"
    DATATABLE = "datatable"
    CALENDAR = "calendar"
    DATEPICKER = "datepicker"
    TIMELINE = "timeline"
    KANBAN = "kanban"
    CAROUSEL = "carousel"
    TABS = "tabs"
    ACCORDION = "accordion"
    MODAL = "modal"
    DRAWER = "drawer"
    TOAST = "toast"
    DROPDOWN = "dropdown"
    NAVBAR = "navbar"
    SIDEBAR = "sidebar"
    FOOTER = "footer"
    HEADER = "header"
    FORM = "form"
    FORM_FIELD = "form_field"
    PROGRESS_BAR = "progress_bar"
    SLIDER = "slider"
    SPINNER = "spinner"
    TOOLTIP = "tooltip"
    POPOVER = "popover"
    BREADCRUMB = "breadcrumb"
    PAGINATION = "pagination"
    SEARCH_BAR = "search_bar"
    FILTER = "filter"
    NOTIFICATION = "notification"
    CHAT_WIDGET = "chat_widget"
    MAP = "map"
    VIDEO = "video"
    AUDIO = "audio"
    EMBED = "embed"
    IFRAME = "iframe"
    SOCIAL_SHARE = "social_share"
    RATING = "rating"
    REVIEW = "review"
    FEEDBACK_FORM = "feedback_form"
    LOGIN_FORM = "login_form"
    SIGNUP_FORM = "signup_form"
    PAYMENT_FORM = "payment_form"
    SUBSCRIPTION_FORM = "subscription_form"
    CONTACT_FORM = "contact_form"
    SEARCH_PAGE = "search_page"
    FILTER_PAGE = "filter_page"
    SORT_PAGE = "sort_page"
    PAGINATION_PAGE = "pagination_page"
    INFINITE_SCROLL = "infinite_scroll"
    VIRTUAL_SCROLL = "virtual_scroll",
    DESCRIPTION = "description"
    Heading = "heading"
    FOOTNOTE = "footnote"
    CAPTION = "caption"
    BLOCKQUOTE = "blockquote"
    PRE = "pre"
    CODE = "code"
    INLINE_CODE = "inline_code"
    QUOTE = "quote"
    PARAGRAPH = "paragraph"
    SUBTITLE = "subtitle"
    TITLE = "title"
    OVERLINE = "overline"
    STRONG = "strong"
    EMPHASIS = "em"
    UNDERLINE = "underline"
    DELETE = "delete"
    INSERT = "insert"
    SUPERSCRIPT = "superscript"
    SUBSCRIPT = "subscript"